### ISSUE TITLE
Help: install failed

### ISSUE THREAD

**Issue by dugugang** [2600hz/kazoo#1193]
I tried to install kazoo in a virtual machine, I got following error.please help.

 - Updating all Bigcouch views with: sup whapps_maintenance migrate
migrating relevant settings from system_config/media_mgr to system_config/media
 - Importing media files with: sup whistle_media_maintenance import_prompts /opt/kazoo/system_media/en-us en-us
ok
 - Creating admin account with: sup crossbar_maintenance create_account "kazoo" "sip.host.voipcloud.com" "kazoo" "kazoo"
failed

**Comment by dschreiber** [comment]
Please use the Google Groups forum for questions. https://groups.google.com/forum/#!forum/2600hz-users
