### ISSUE TITLE
Looks like a typo in get_all_account_mods and some functions further

### ISSUE THREAD

**Issue by onnet** [2600hz/kazoo#1293]
https://github.com/2600hz/kazoo/blob/master/core/whistle_apps-1.0.0/src/whapps_util.erl#L241-L243

get_all_account_mods(Encoding) ->
    {'ok', Databases} = couch_mgr:db_info(),
    [wh_util:format_account_id(Db, Encoding) || Db <- Databases, is_account_mod(Db)].

get_all_account_mods/1 is aimed to provide modbs, but formats it to account_db: wh_util:format_account_id

wh_util:format_account_modb/2 should be used instead.

As a result sup kazoo_modb_maintenance delete_modbs 201508 fails to run

**Comment by lazedo** [comment]
@onnet thanks Kirill
