### ISSUE TITLE
cb_vmboxes broken a bit

### ISSUE THREAD

**Issue by onnet** [2600hz/kazoo#1307]
https://github.com/2600hz/kazoo/blob/master/applications/crossbar/src/modules/cb_vmboxes.erl#L422

kzd_voicemail_box:timezone(<<"timezone">>, Doc)

But kzd_voicemail_box:timezone/2 says it wants:

timezone(Box) ->
    timezone(Box, 'undefined').
timezone(Box, Default) ->
    case wh_json:get_value(?KEY_TIMEZONE, Box) of
        'undefined'   -> owner_timezone(Box, Default);
        <<"inherit">> -> owner_timezone(Box, Default);  %% UI-1808
        TZ -> TZ
    end.

So, if I am not wrong 

kzd_voicemail_box:timezone(<<"timezone">>, Doc)

should be changed to 

kzd_voicemail_box:timezone(Doc)

Regards,

**Comment by lazedo** [comment]
@onnet your evaluation seems correct. please file a bug in jira. tks
