### ISSUE TITLE
GUI link in README points to kazoo-ui - shouldn't it point to monster-ui repo?

### ISSUE THREAD

**Issue by webrtcdev1** [2600hz/kazoo#1706]
And also contain instructions for installing all monster apps?

**Comment by neurosys-zero** [comment]
Kazoo-UI is the first UI 2600hz developed and released for the Kazoo platform. 

Monster-UI is the successor to Kazoo-UI, which allows for a more abstract foundation and modular apps approach. This way developers can create their own apps within Monster and add their "special sauce"

I do believe the basic install instructions for Monster Apps are in the docs folder: https://github.com/2600hz/monster-ui/tree/master/docs

Maybe it needs a clean up? :)

**Comment by jamesaimonetti** [comment]
Yes, I'm working on better installation instructions and will include the link to the monster apps install guide.

**Comment by k-anderson** [comment]
Howdy,

Thanks for the heads up!  The README was updated so I am going to close this out but if you have any other comments or can't find something you need let us know!
