### ISSUE TITLE
Blackhole subscription.

### ISSUE THREAD

**Issue by kysonic** [2600hz/kazoo#1750]
Hello! Could sombody please answer on my questions: 

1. Would subscription die if auth token would have expired?
2. How long will certain subscription live?

To clarify my personal situation: I have a node.js server and permanent connection with blackhole. 

Many thanks for considering my request.

**Comment by Mike-Dunton** [comment]
1. After looking at the code it looks like once your subscribe to an event you are auth'd to the channel forever. However I see one exception when sending a "send_amqp" event on the socket. That requires a valid auth token every time. 

2. It looks like the subscription will live forever as long as your websocket connection is open. 

I recommend building into your app someway to reauth incase the connection gets interrupted.  Here is the documentation on that. 
https://2600hz.atlassian.net/wiki/display/APIs/Generating+an+Authentication+Token

**Comment by kysonic** [comment]
@Mike-Dunton Thanks a lot!
