### ISSUE TITLE
Blacklist not normalizing incoming CID, therefore not working

### ISSUE THREAD

**Issue by bazemoreb** [2600hz/kazoo#1826]
Hi there,

Previously blacklist numbers could be added as npan (10 digit) so that the numbers would be matched.  Looks like recently this was updated so on entry they are normalized to e.164.

You guys seem to have fixed in master using the new knm_util, but on 3.22, stepswitch is not normalizing the CID number of the calling party, so therefore no numbers are matching, see below (from /applications/stepswitch/src/stepswitch_inbound.erl) :

%%--------------------------------------------------------------------
%% @private
%% @doc
%%
%% @end
%%--------------------------------------------------------------------
-spec is_blacklisted(wh_json:object()) -> boolean().
is_blacklisted(JObj) ->
    AccountId = wh_json:get_ne_value(?CCV(<<"Account-ID">>), JObj),
    case get_blacklists(AccountId) of
        {'error', _R} ->
            lager:debug("not blacklisted ~p", [_R]),
            'false';
        {'ok', Blacklists} ->
            Blacklist = get_blacklist(AccountId, Blacklists),
**          Number = wh_json:get_value(<<"Caller-ID-Number">>, JObj),**
            case wh_json:get_value(Number, Blacklist) of
                'undefined' ->
                    lager:debug("~p not blacklisted, did not match any rule", [Number]),
                    'false';
                _Rule ->
                    lager:info("~p is blacklisted", [Number]),
                    'true'
            end
    end.

To fix, I believe Number = just needs to use wh_util:normalize to convert to e.164.  I wasn't sure if we should do a PR against 3.22 or not as more of a bug?  LMK.  Thanks!

**Comment by jamesaimonetti** [comment]
Hi @bazemoreb you are correct and it has been addressed in #1811 Once accepted, a new build of 3.22 will be created with the fix.

**Comment by bazemoreb** [comment]
Beauty - thank you sir.
