### ISSUE TITLE
Issues with making with 19.0

### ISSUE THREAD

**Issue by kostis** [2600hz/kazoo#2171]
After contributing quite some code modifications, I decided it's about time to actually make kazoo for the first time ;) Mind you I am using 19.0, which might explain some issues below.

First of all, I noticed this:
<pre>
 DEP    proper
 CONF   proper (proper)
Using Erlang's 'random' ('rand' in 19.0 and later) module
../erlang.mk:4645: recipe for target '/home/kostis/HiPE/kazoo/deps/proper' failed
make[1]: [/home/kostis/HiPE/kazoo/deps/proper] Error 1 (ignored)
</pre>
which is strange, because PropEr builds alright with 19.0  (but I've never tried to build it with erlang.mk though).  Can you investigate why this is so?

As the last line mentions, this error is ignored and make continues.

It doing so, the make then fails with:
<pre>
 ERLC   couchbeam.erl couchbeam_app.erl couchbeam_attachments.erl couchbeam_changes.erl couchbeam_changes_stream.erl couchbeam_changes_sup.erl couchbeam_doc.erl couchbeam_ejson.erl couchbeam_httpc.erl couchbeam_sup.erl couchbeam_util.erl couchbeam_uuids.erl couchbeam_view.erl couchbeam_view_stream.erl couchbeam_view_sup.erl gen_changes.erl
src/couchbeam_util.erl:136: syntax error before: '/'
src/couchbeam_util.erl:140: syntax error before: '/'
../../erlang.mk:5009: recipe for target 'ebin/couchbeam.app' failed
make[3]: *** [ebin/couchbeam.app] Error 1
../../erlang.mk:4827: recipe for target 'app' failed
make[2]: *** [app] Error 2
make[2]: Leaving directory '/home/kostis/HiPE/kazoo/deps/couchbeam'
../erlang.mk:4137: recipe for target 'deps' failed
make[1]: *** [deps] Error 2
make[1]: Leaving directory '/home/kostis/HiPE/kazoo/deps'
Makefile:54: recipe for target 'deps' failed
make: *** [deps] Error 2
</pre>
This is because `couchbase` uses an outdated (and in 19.0 obsolete) spec syntax.
You may want to notify the corresponding developers.

Similar problems (many) exist for [hamcrest](https://github.com/hyperthunk/hamcrest-erlang/)  But this project two days ago was updated to fix its specs...  I am not sure what's happening here.  I will continue the make once the hamcrest issue is fixed.

But I would appreciate some investigation on what goes wrong in the making of PropEr.

**Comment by kostis** [comment]
OK, the hamcrest issue is because [wsecli](https://github.com/madtrick/wsecli/blob/master/rebar.config) insists to get a specific SHA of `hamcrest` instead of the current `master`.  This needs to be fixed there.  I am cc:ing @madtrick

**Comment by fenollp** [comment]
@kostis wrt PropEr: I am baffled. From what I gather [we use erlang.mk @ master](https://github.com/2600hz/kazoo/blob/master/Makefile#L51) which fetches [default PropEr](https://github.com/2600hz/kazoo/blob/master/make/deps.mk#L4) @ [master](https://github.com/ninenines/erlang.mk/blob/master/index/proper.mk#L7).

**Comment by kostis** [comment]
Me too.  Can you at least confirm whether you also get the
<pre>../erlang.mk:4645: recipe for target '/home/kostis/HiPE/kazoo/deps/proper' failed</pre>
message or it's something that happens only on my system?

**Comment by fenollp** [comment]
I do get the same message on my system @kostis

**Comment by fenollp** [comment]
Progress update: couchbeam fix merged by @benoitc, will update once a release is out.

**Comment by johnnybubonic** [comment]
it appears that current master branch's HEAD still seems to get build failures:

make[3]: Leaving directory '/opt/kazoo/deps/fusco'
make[3]: Entering directory '/opt/kazoo/deps/wsecli'
make[4]: Entering directory '/opt/kazoo/deps/hamcrest'
 ERLC   hamcrest.erl hamcrest_matchers.erl hamcrest_term.erl
src/hamcrest.erl:59: syntax error before: '/'
src/hamcrest.erl:63: syntax error before: '/'
src/hamcrest.erl:67: syntax error before: '/'
src/hamcrest.erl:72: syntax error before: '/'
src/hamcrest.erl:79: syntax error before: '/'
src/hamcrest.erl:90: syntax error before: '/'
src/hamcrest.erl:108: syntax error before: '/'
make[5]: *** [../../erlang.mk:5043: ebin/hamcrest.app] Error 1
make[4]: *** [../../erlang.mk:4860: app] Error 2
make[4]: Leaving directory '/opt/kazoo/deps/hamcrest'
make[3]: *** [../../erlang.mk:4180: deps] Error 2
make[3]: Leaving directory '/opt/kazoo/deps/wsecli'
make[2]: *** [../../erlang.mk:4180: deps] Error 2
make[2]: Leaving directory '/opt/kazoo/deps/escalus'
make[1]: *** [../erlang.mk:4179: deps] Error 2
make[1]: Leaving directory '/opt/kazoo/deps'
make: *** [Makefile:56: deps] Error 2

Using erlang 19.1.1

**Comment by fenollp** [comment]
@johnnybubonic Thanks for noticing!
It's on the way: https://github.com/esl/escalus/issues/125
