### ISSUE TITLE
Deleting a callflow with the account id as a callflow id... deletes the account.

### ISSUE THREAD

**Issue by brooksc** [2600hz/kazoo#2535]
We hit the following self-inflicted issue today on Kazoo 3.2.2

» 8 Sep 2016 14:25:30.163  <redacted> 2600hz[28467]: [[info]] |e8d9d252347e46134e9f0ab69c623efb|api_resource:110 (<0.5761.3>) DELETE: /v1/accounts/3a852fb3995a24b863bb090447405715/callflows/3a852fb3995a24b863bb090447405715? from <redacted>
» 8 Sep 2016 14:25:30.208  <redacted> 2600hz[28467]: [[debug]] |e8d9d252347e46134e9f0ab69c623efb|crossbar_doc:172 (<0.5761.3>) doc 3a852fb3995a24b863bb090447405715(11-e14cf5201f44d8d9ef4b5a2b50ab75bb) is soft-deleted, returning bad_identifier

a developer accidentally passed in the account id as the callflow id.  We later discovered this resulted in soft deleting the account.

We really wish that instead Kazoo returned an error corresponding to a call flow with that id wasn't found... :)

**Comment by tsromana** [comment]
@brooksc i guess this issue is fixed in kazoo v4 where the doc is type checked to make sure it is not some other type of doc as in your case an account doc instead of a callflow doc

**Comment by lazedo** [comment]
thanks @tsromana for the comment. closing this.
