### ISSUE TITLE
blackhole documentation error

### ISSUE THREAD

**Issue by fredguth** [2600hz/kazoo#2853]
Just testing Kazoo 4.0 for the first time.
I was in this documentation README:
https://github.com/2600hz/kazoo/blob/master/applications/blackhole/doc/README.md

There is an error in the code there. Blackhole expects the accountId and binding to be inside data.  So, the correct code is:
`send({
                    action: 'subscribe',
                    auth_token: '{AUTH_TOKEN}',
                    data: {
                        account_id: '{ACCOUNT_ID}',
                        binding: 'call.CHANNEL_CREATE.*'
                    }
            });`

**Comment by dschreiber** [comment]
Please submit a pull request on that file.
