### ISSUE TITLE
Cannot add SIP Trunk provider

### ISSUE THREAD

**Issue by emnvn** [2600hz/kazoo#3042]
Hello,

I have deployed Kazoo tags/3.22.68, I tried to connect my Kazoo instance to a SIP Trunk provider but I don't know how to do it. In version 3.22.29 I can add SIP trunk provider in Carrier modules with Kazoo-UI. But this version use Monser-UI, I can not find that module. I have seen a note of "This will route the calls to the carriers set up for this account via the Carriers app." but I can not find this app in Monster-UI.

I hope that someone show to me how can I do that.

Thanks very much.

**Comment by dschreiber** [comment]
Hi Andrew,
     Thanks for your interest in the project. We do not use Github for communication / issues, we have a mailing list for that (which is fairly active). Please re-post your question there.  https://groups.google.com/forum/#!forum/2600hz-users . If you are trying to customize Kazoo software code itself you can also try https://groups.google.com/forum/#!forum/2600hz-dev 

(Unfortunately we can't disable the issues section in Github)

Thanks for your interest!
