### ISSUE TITLE
Pivot issues status

### ISSUE THREAD

**Issue by andrewreedy** [2600hz/kazoo#3221]
For our application we want to use the Pivot functionality pretty extensively. So far the experience has been unreliable, I'm guessing due to known issues. I've attempted to use both the `play` and `say` modules without success with both Kazoo JSON and Twiml.

We want to be able to do things like modern phone systems which use NLP rather than traditional IVR's. ex. What are you calling about today? [pause] Wait for speech input -> send to server process -> reply with mp3 url / `say` module. However we may have to explore other options for this. 

I came across this [issue dump](https://docs.2600hz.com/dev/applications/pivot/doc/issues/). It would be nice if this was trackable and more detailed so we can tell what works and what doesn't.

**Comment by dschreiber** [comment]
Hi Andrew,
     Thanks for your interest in the project. We do not use Github for communication / issues, we have a mailing list for that (which is fairly active). Please re-post your question there.  https://groups.google.com/forum/#!forum/2600hz-users . If you are trying to customize Kazoo software code itself you can also try https://groups.google.com/forum/#!forum/2600hz-dev 

FYI the link you have found in the "issue dump" is actually quite old also, that doc site is in the process of being updated. If you hop on the mailing list and post specific examples of what you want, I can try to help you there.

(Unfortunately we can't disable the issues section in Github)

Thanks for your interest!
