### ISSUE TITLE
Problem no_route_response

### ISSUE THREAD

**Issue by emnvn** [2600hz/kazoo#3250]
Hello,

I have a ClickToCall definition that will connect a PSTN phone number to a audio file (It take  about 7 seconds to play this audio file) I have make a load test to know how many calls that kazoo can handle. The result that when number of calls is about 15 or greater I see some calls auto hangup (hangup before playing audio file) with status of NO_ROUTE_RESPSONSE.

I traced the log, I saw the timeout happen in this code (file cf_route_req.erl) happen because processing time is greater than 3 seconds

> send_route_response(Flow, JObj, Call) ->
>     lager:info("callflows knows how to route the call! sending park response"),
>     AccountId = whapps_call:account_id(Call),
>     Resp = props:filter_undefined(
>              [{?KEY_MSG_ID, wh_api:msg_id(JObj)}
>               ,{?KEY_MSG_REPLY_ID, whapps_call:call_id_direct(Call)}
>               ,{<<"Routes">>, []}
>               ,{<<"Method">>, <<"park">>}
>               ,{<<"Transfer-Media">>, get_transfer_media(Flow, JObj)}
>               ,{<<"Ringback-Media">>, get_ringback_media(Flow, JObj)}
>               ,{<<"Pre-Park">>, pre_park_action(Call)}
>               ,{<<"From-Realm">>, wh_util:get_account_realm(AccountId)}
>               ,{<<"Custom-Channel-Vars">>, whapps_call:custom_channel_vars(Call)}
>               | wh_api:default_headers(?APP_NAME, ?APP_VERSION)
>              ]),
>     ServerId = wh_api:server_id(JObj),
>     Publisher = fun(P) -> wapi_route:publish_resp(ServerId, P) end,
>     case wh_amqp_worker:call(Resp
>                              ,Publisher
>                              ,fun wapi_route:win_v/1
>                              ,?ROUTE_WIN_TIMEOUT
>                             )
>     of
>         {'ok', RouteWin} ->
>             lager:info("callflow has received a route win, taking control of the call"),
>             cf_route_win:execute_callflow(RouteWin, whapps_call:from_route_win(RouteWin, Call));
>         {'error', _E} ->
>             lager:info("callflow didn't received a route win, exiting : ~p", [_E])
>     end.

I have take many days to  troubleshoot but I can't see any bottle neck. I have think that it may be the problem of rabbitmq-server but I not sure a bout that.

I use kazoo 3.22-59 that deploy on one server (8 CPU, 8 GB RAM)

Hope any help

Thanks very much!

**Comment by jamesaimonetti** [comment]
Hi @emnvn, we don't really use github issues so you're not going to get a response here. Please ask questions on the google group (2600hz-users). Thanks!
