### ISSUE TITLE
Error of ecallmgr  because of a bad field User-Agent

### ISSUE THREAD

**Issue by lexfer** [2600hz/kazoo#658]
kamctl ul show:

Domain:: location table=512 records=1 max_slot=1
AOR:: camera-sip@host.host.host.ru
Contact:: sip:camera-sip@172.18.0.201:5060 Q=
Expires:: 42
Callid:: 854878693-5060-1@172.18.0.201
Cseq:: 9551

User-agent:: Grandstream `"3611HD(IPC) 1.0.4.50

Received:: sip:x.x.x.x:2269
State:: CS_SYNC
Flags:: 0
Cflag:: 6
Socket:: udp:x.x.x.x:5060
Methods:: 8159
Ruid:: uloc-548684f4-22f-2
Reg-Id:: 0
Last-Keepalive:: 1418122790
Last-Modified:: 1418122790

rabbitmq-message:

{"Network-Port":"5060","Network-IP":"x.x.x.x",
"Kamailio-Hostname":"kamailio1.host.host.com",
"RPid":"unknown","To-Host":"host..host.host.com",
"To-User":"camera-sip",
"From-Host":"host.com",
"From-User":"camera-sip",
"Presence-Hosts":"n/a",
"Profile-Name":"sipinterface_1",
"Call-ID":"854878693-5060-1@172.18.0.201",

"User-Agent":"Grandstream `".3611HD(IPC)1.0.4.50",

"Status":"Registered(udp)",
"Realm":"host.com",
"Username":"camera-sip",
"Expires":"46",
"Contact":"\"camera-sip\"
<sip:camera-sip@x.x.x.x:2269;
fs_path=<sip:x.x.x.x:5060;
lr;received='sip:x.x.x.x:2269'>>",
"Event-Timestamp":"63585341485",
"Server-ID":"",
"Node":"kamailio@host.com",
"Msg-ID":"5986456e0e989232-609@x.x.x.x",
"App-Version":"4.0.6",
"App-Name":"kamailio",
"Event-Name":"reg_success",
"Event-Category":"directory"}

and at the same time ecallmgr log:

Dec  9 17:13:18 logic2 2600hz[678]: |0000000000|Undefined:Undefined (emulator)
Error in process <0.4869.0> on node 'ecallmgr@logic2.voip.private' with exit
value: {{nocatch,{error,"lexical error: invalid char in json
text.\n"}},[{wh_json,try_converting,2,[{file,"src/wh_json.erl"},{line,131}]},{gen_listener,handle_event,4,[{file,"src/gen_listener.erl"},{line,569}]}]}#012#012

**Comment by jamesaimonetti** [comment]
@lazedo did you ever look into this? Is the Kamailio JSON encoder able to handle the User-Agent in the example above?

@lexfer sorry to be delayed on this! Typically reports like this should go either to the mailing list (2600hz-dev or 2600hz-users on Google Groups) or to the [ticketing system](http://tickets.2600hz.com) to be reviewed.

**Comment by lexfer** [comment]
The Grandstream 3611HD device on kamailio is registered but kazoo of the logician reports about a mistake. As kazoo writes about a mistake to json, the logic doesn't know about this registration, the entering call for this device doesn't pass. Possibly, some of symbols in the field: "Grandstream`". 3611HD(IPC)1.0.4.50" leads to a mistake. This field can't be corrected on the device.
