### ISSUE TITLE
erlang versions nightmare

### ISSUE THREAD

**Issue by acrixl** [2600hz/kazoo#785]
what version of erlang curently recomended for latest kazoo?

i try R14B03 as in doc
but get some issues with predcompiled rebar (and why it is predcompiled?)
and: cowboy_middleware.erl:20: bad attribute

i try R16B03 but get some errors when compile bigcouch

**Comment by jamesaimonetti** [comment]
R15B03-1 is the supported version atm. Hoping to get R16B03 support sometime this year.
